name: Build Tweak

on: [workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          export THEOS=~/theos
          rm -rf $THEOS
          git clone --depth 1 https://github.com/theos/theos.git $THEOS
          cd $THEOS
          git submodule update --init --recursive
          git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks
          
      - name: Build Package
        run: |
          export THEOS=~/theos
          # 显式指定 SDK，防止 Theos 找不到默认 SDK
          make package FINALPACKAGE=1 SYSROOT=$THEOS/sdks/iPhoneOS14.5.sdk
        
      - name: Extract Dylib
        run: |
          mkdir -p extracted
          DEB_FILE=$(ls packages/*.deb | head -n 1)
          ar x $DEB_FILE
          tar -xf data.tar.*
          cp Library/MobileSubstrate/DynamicLibraries/*.dylib extracted/
          cp Library/MobileSubstrate/DynamicLibraries/*.plist extracted/

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: TelegramSiriFix-deb
          path: packages/*.deb

      - name: Upload Dylib & Plist
        uses: actions/upload-artifact@v4
        with:
          name: TelegramSiriFix-Dylib-Files
          path: extracted/*
